apiVersion: v1
kind: Service
metadata:
  labels:
    app: jpcom
  name: jpcom-service
spec:
  selector:
    app: jpcom-deployment
  sessionAffinity: None
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3000
