apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpcom-deployment
  labels:
    app: jpcom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpcom
  template:
    metadata:
      labels:
        app: jpcom
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: jpcom
        image: japiirainen/jpcom:latest
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {} 
            