apiVersion: v1
kind: Service
metadata:
  labels:
    app: jpcom
  name: jpcom
spec:
  selector:
    app: jpcom
  sessionAffinity: None
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
