apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpcom-deployment
  labels:
    app: jpcom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpcom
  template:
    metadata:
      labels:
        app: jpcom
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: jpcom
        image: japiirainen/jpcom:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {} 

---            

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jpcom
  name: jpcom-service
spec:
  selector:
    app: jpcom-deployment
  sessionAffinity: None
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3000
