apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpcom-deployment
  labels:
    app: jpcom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jpcom
  template:
    metadata:
      labels:
        app: jpcom
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: jpcom
        image: japiirainen/jpcom:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /manifest.json
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10        
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /manifest.json
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 10
            timeoutSeconds: 10
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: 
          requests:
            cpu: 1000m
            memory: 1G
    
            